# Generated by Django 4.1 on 2022-08-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('work', models.CharField(max_length=50, verbose_name='work')),
                ('img', models.ImageField(upload_to='workers/', verbose_name='Картинка:')),
            ],
            options={
                'verbose_name': 'Повар',
                'verbose_name_plural': 'Повара',
            },
        ),
    ]
