# Generated by Django 4.1 on 2022-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='workers',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='workers',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='twitte'),
        ),
    ]
