# Generated by Django 4.1 on 2022-08-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_workers_facebook_workers_instagram_workers_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='name',
            new_name='fname',
        ),
    ]
