# Generated by Django 4.1 on 2022-08-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_name_workers_fname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers',
            new_name='WorkersModels',
        ),
    ]
