# Generated by Django 4.1 on 2022-08-08 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_workers_workersmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='имя')),
                ('gmail', models.EmailField(max_length=50, verbose_name='вам gmail')),
                ('persons', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='количество персон')),
                ('numbers', models.CharField(max_length=14, verbose_name='ваш номер')),
                ('message', models.TextField(max_length=300, verbose_name='ваше сообщение')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.CharField(blank=True, max_length=20, verbose_name='время брони')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
