# Generated by Django 4.0.5 on 2022-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='имя')),
                ('work', models.CharField(max_length=100, verbose_name='работает в')),
                ('text', models.TextField(verbose_name='сообщение')),
                ('img', models.ImageField(upload_to='workers/', verbose_name='Картинка:')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, max_length=30, verbose_name='время брони'),
        ),
    ]
