# Generated by Django 4.0.5 on 2022-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_feedback_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(choices=[('1', '1 person'), ('2', '2 person'), ('3', '3 person'), ('4', '4 person'), ('5', '5 person'), ('6', '6 person')], default=('1', '1 person'), verbose_name='количество персон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, choices=[('09:00', '09:00AM'), ('10:00', '10:00AM'), ('11:00', '11:00AM'), ('13:00', '01:00PM'), ('14:00', '02:00PM'), ('15:00', '03:00PM'), ('16:00', '04:00PM'), ('17:00', '05:00PM'), ('18:00', '06:00PM'), ('19:00', '07:00PM'), ('20:00', '08:00PM'), ('21:00', '09:00PM'), ('22:00', '10:00PM')], default=('09:00', '09:00AM'), max_length=30, verbose_name='время брони'),
        ),
    ]
