# Generated by Django 4.0.5 on 2022-08-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_booking_persons_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(choices=[('1 person', '1'), ('2 person', '2'), ('3 person', '3'), ('4 person', '4'), ('5 person', '5'), ('6 person', '6')], default=('1 person', '1'), verbose_name='количество персон'),
        ),
    ]
