# Generated by Django 4.0.5 on 2022-08-09 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_booking_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='количество персон'),
        ),
    ]
